name = HanumanMini
version = 1.0.5
author = ArtronAcademy
maintainer = Chanatip112 <nackchanatip112@gmail.com>
sentence = Library for HanumanMini
paragraph = Robot Control Board
category = Device Control
url = https://github.com/Chanatip112/HanumanMini
architectures = *
